### ISSUE TITLE
YYG model: incorrect cumulative deaths values

### ISSUE THREAD

**Issue by youyanggu** [pyliu47/covidcompare#1]
Hi all,

Thanks for making this public and for your work on this.

It seems like for the YYG model, you guys are using the incorrect values the cumulative deaths. See image below for an example of the Wyoming projections from 2020-05-10. The projections used in this evaluation is quite different than the original data source (https://github.com/youyanggu/covid19_projections/blob/master/projections/2020-05-10/US_WY.csv). Refer to the below screenshot.

![Wyoming difference](https://user-images.githubusercontent.com/1267035/87481725-e81f8900-c5fd-11ea-908d-2e320bbcd3e0.png)

As for the root cause, it seems like the YYG model is processed differently than the other models: https://github.com/pyliu47/covidcompare/blob/master/code/1_pull_data.r#L392.

![Screen Shot 2020-07-14 at 6 11 38 PM](https://user-images.githubusercontent.com/1267035/87482226-f3bf7f80-c5fe-11ea-9c98-4c7054aaf20c.png)

You guys try to collate cumulative deaths by taking the cumulative sum of the daily deaths rather than directly using the cumulative death projections presented. This causes a series of propagating rounding errors, as the example above shows. The cumulative deaths projections have been available since 2020-04-03, so I think it would be more appropriate to directly use the raw cumulative deaths projections to avoid the aforementioned discrepancies. This would also bring the processing methodology in line with the rest of the models (with available cumulative deaths data).

This discrepancy normally wouldn't cause a large variation in the results, since it is only apparent in regions with few reported deaths. But because this particular evaluation uses median absolute percentage errors, small discrepancies such as this can cause large variations in the MAPE. In the above example, the correct MAPE for 4 weeks out should be 24% (predicted: 13, actual: 17), but it is currently computed as 59% (predicted: 7, actual: 17). There are numerous other regions where this discrepancy is non-significant - I can put together a list if desired. So I'd appreciate it if you can update the code to use the correct cumulative death projections.

Thank you for your time; I look forward to your response.

**Comment by Joseph-Friedman** [comment]
Hi Youyang, thanks for bringing this to our attention. As you explain above, the framework we released with our preprint manuscript used your public, daily death estimates, both directly and after summing them, to assess errors in total cumulative death forecasts. 

When originally incorporating your estimates, we noticed that not all of the files had estimates of cumulative deaths, so we used your daily deaths. Thank you for fixing this issue, so that we can now include your cumulative deaths directly. 

By using only one input data source from each model, and converting between daily and cumulative deaths, our framework creates an internally consistent environment, and it assumes that models are also internally consistent. 

If you are concerned that rounding errors are affecting the internal consistency of your published results, we would recommend that you release decimal points, so that estimated can be aggregated by other researchers in an accurate fashion, e.g. country-specific up to regions, daily summed to weekly, etc. 

You can now find a set of results on our GitHub that reflect the change you requested. You’ll be happy to see that this change has had a very minor impact on the predictive validity results, as would be expected; rounding errors should be zero-centered. 

We appreciate your attention to our work, and we hope you will stay engaged as we continue to improve our framework and release new analyses. A new version of our preprint will be available soon that also reflects the above changes.

**Comment by youyanggu** [comment]
Hi Joseph,

I really appreciate you taking the time to respond and update the evaluation. Your explanation makes a lot of sense, and I'm glad that the change only had a minor impact. Most importantly, I'm glad that the input data now accurately reflect the raw data.

And thank you for your suggestions regarding rounding errors. I will look into including decimal points in our GitHub repo to avoid similar issues in the future.

This is the first work I've seen that standardizes global forecasts from various groups, so I hope other researchers can build on top of this in the coming weeks/months.

Best,
Youyang
